#!/usr/bin/python
# Copyright (c) 2015 Adabassar Sustainable Industries
# Author: Ugur Demir
import os
import subprocess
import RPi.GPIO as GPIO
import time
from time import sleep
 
GPIO.setmode(GPIO.BCM)
 
GPIO.setwarnings(False)
import sys
 
import Adafruit_DHT
k = 0
l = 0
 
GPIO.setup(23, GPIO.OUT)
GPIO.output(23, GPIO.HIGH)
 
while 1 :
    sensor_args = { '11': Adafruit_DHT.DHT11,
                   '22': Adafruit_DHT.DHT22,
                   '2302': Adafruit_DHT.AM2302 }

if len(sys.argv) == 3 and sys.argv[1] in sensor_args:
    sensor = sensor_args[sys.argv[1]]
    pin = sys.argv[2]
else:
    print 'usage: sudo ./Adafruit_DHT.py [11|22|2302] GPIOpin#'
    print 'example: sudo ./Adafruit_DHT.py 2302 4 - Read from an AM2302 connected to GPIO #4'
    sys.exit(1)


# Try to grab a sensor reading. Use the read_retry method which will retry up
# to 15 times to get a sensor reading (waiting 2 seconds between each retry).
humidity, temperature = Adafruit_DHT.read_retry(sensor, pin)
 
# Un-comment the line below to convert the temperature to Fahrenheit.
# temperature = temperature * 9/5.0 + 32
print 'Sicaklik={0:0.1f}* Humidity={1:0.1f}%'.format(temperature, humidity)
 
sic = temperature
 
if sic >= 24 :
    if k == 0:
        GPIO.output(23, GPIO.LOW)
        time.sleep(1)
        GPIO.output(23, GPIO.HIGH)
    k = 1
    l=0

 
    else:
        if l == 0:
            GPIO.output(23, GPIO.LOW)
            time.sleep(1)
            GPIO.output(23, GPIO.HIGH)
        k = 0
        print 'sicaklik24 uzeri'
        l = 1
